### PR TITLE
Feature/add requirements

### PR DESCRIPTION
**Pull request by junguchina**
* Add: add requirements.txt for moudule management
* Modify: should use python3 to run the scripts
* Del: remove the unused module import

### CODE REVIEW

**Comment by junguchina** [comment]
When use the python3 to run this project, there are three ImportErrors output.
So I suggest to add requirements.txt for moudule management.

**Comment by threadshare** [comment]
Good idea, but now maybe we don't need this. I suggest that we should use the standard library to develop as much as possible, so that developers who do not understand python can directly run the program without downloading additional libraries. @winlin

**Comment by EOSBIXIN** [comment]
@junguchina could you remove the unused import in you branch, I forget to clean the demo script, tks.

I think requirements.txt is needed, bacause there are lots of testcase scripts may use other libraries, so  requirements.txt is a collection.

**Comment by threadshare** [comment]
And maybe you're not using the latest code. The latest code doesn't have this part of the code anymore. Please check it. @junguchina

**Comment by junguchina** [comment]
@EOSBIXIN Ok, I will try to remove the unused import and keep the file requirements.txt.

**Comment by junguchina** [comment]
@GiggleAll The code is the latest from master.Maybe I use ubuntu to run this project, so some modules need to be installed when use python3.

**Comment by junguchina** [comment]
@EOSBIXIN Now this branch can be merged, the demo scripts passed in my local.

**Comment by threadshare** [comment]
@junguchina  Thanks for your work.  It's run better.

**Pull request merged**
